Implement the backwards-compatibility rule
HL7/cda-ccda-2.1 pull request #1
Opened 2021-07-19 17:45 UTC by benjaminflessner

Implements: https://jira.hl7.org/browse/CDA-758

Whenever any of the C-CDA 2.1 versioned templateIds (with extensions) are present in one of the C-CDA document-level templates, their associated C-CDA 1.1 templateId must also be present.

This was done by exporting the list of all templateIds in C-CDA 2.1, filtering out those which did not have a 1.1 equivalent, and creating a single rule whose context is any of those templateIds. In the rule, a 2nd templateId is required without the extension, but only if the document itself is one of the 13 base C-CDA document templates.

The included sample CCD file still validates, and you can check that the rule fires by removing any of the non-document-level C-CDA 1.1 templateIds in the document (that are paired with a new 2.1 version).

2021-07-19 21:53 UTC, mjszczep requested changes
Two comments:

1. It looks like your list is missing the templateId `2.16.840.1.113883.10.20.22.2.11.1:2015-08-01` (the [Discharge Medications Section (entries required)](https://hl7.org/ccdasearch/templates/2.16.840.1.113883.10.20.22.2.11.1.html)). Should that be included?
2. Performance-wise, I don’t know whether the contains(huge list…) approach is faster or slower than `"@root='first root' or @root='second root' or…"` but if there’s any way to determine whether one of those has significant advantages over the other, we should probably take that into consideration.

2021-07-19 23:28 UTC, mjszczep commented
Actually, from playing with this a bit it looks like the `contains` approach you're using is indeed the better one, so I guess that really only leaves the first question.

(I decided to see how Oxygen handled a ridiculously scaled-up version of this with 10,000 66-char strings. The `contains` version worked fine but trying to match them individually caused a stack overflow. 😆)

2021-07-20 13:47 UTC, benjaminflessner commented
> 1. It looks like your list is missing the templateId `2.16.840.1.113883.10.20.22.2.11.1:2015-08-01` (the [Discharge Medications Section (entries required)](https://hl7.org/ccdasearch/templates/2.16.840.1.113883.10.20.22.2.11.1.html)). Should that be included?

Good eye! At first I thought perhaps C-CDA 1.1 didn't have this template, but sure enough it does.

2021-07-20 15:35 UTC, mjszczep approved these changes

2021-07-29 13:37 UTC, merged